name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

      
permissions:
  contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Remove old docs folder
        run: rm -rf docs

      - name: Build the app
        run: npx expo export --platform web

      - name: Rename dist to docs
        run: mv dist docs

      - name: Copy index.html to 404.html
        run: cp docs/index.html docs/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
